### ISSUE TITLE
Code about Text-Frame Attention Encoder

### ISSUE THREAD

**Issue by ZhanYang-nwpu** [jpthu17/DiffusionRet#1]
Hello,

Thank you for your hard work and excellent contribution. Your work has been truly inspiring. 
However, I have a question regarding section 3.2.1 of the paper, specifically the "Text-Frame Attention Encoder" mentioned in the discussion about aggregating frame representation. The final video representation is defined as Formula 4. However, I couldn't find any implementation of the text-frame attention encoder in the code. It seems that the get_video_feat function in the code uses the self.agg_video_feat function to aggregate video frames, which relies on seqTransf without any input for text features. 
Could you please verify this discrepancy and provide an explanation?

Thank you!

**Comment by jpthu17** [comment]
Hi Yang Zhan,

Thank you for your interest in our work. The code of "Text-Frame Attention Encoder" is here:

https://github.com/jpthu17/DiffusionRet/blob/8627feef43108e8c691719847939536898b0bd7b/DiffusionRet/models/diffusion.py#L40-L43

**Comment by ZhanYang-nwpu** [comment]
> Hi Yang Zhan,
> 
> Thank you for your interest in our work. The code of "Text-Frame Attention Encoder" is here:
> 
> https://github.com/jpthu17/DiffusionRet/blob/8627feef43108e8c691719847939536898b0bd7b/DiffusionRet/models/diffusion.py#L40-L43



Thank you very much. I understand.
