### ISSUE TITLE
Question about how to get the ground truth x0？

### ISSUE THREAD

**Issue by chuanshen-chen** [jpthu17/DiffusionRet#5]
Hello, I would like to ask how x0 (ground truth) in formula 8 and formula 9 in the article is obtained?

**Comment by chuanshen-chen** [comment]
maybe the distribution x_start is the ground truth [1,0,0,0,0,0,0]，which means only the video which matters the query is one，others are all zeros?

**Comment by jpthu17** [comment]
> maybe the distribution x_start is the ground truth [1,0,0,0,0,0,0]，which means only the video which matters the query is one，others are all zeros?

You're right. That's exactly what we do.
