### ISSUE TITLE
Question about what is the x_start(the init distribution) when inferencing?

### ISSUE THREAD

**Issue by chuanshen-chen** [jpthu17/DiffusionRet#6]
How to get the x_start(the init distribution) when inferencing? In an other word, how to get x_k to input it to the model when inferencing？

**Comment by jpthu17** [comment]
> How to get the x_start(the init distribution) when inferencing? In an other word, how to get x_k to input it to the model when inferencing？

I'm sorry, I don't quite understand the intent of inputting x_0 when inferencing. When inferencing, diffusion models gradually denoise from noise to x_0. In other words, the input to the diffusion model is noise and the output is x_0.

**Comment by chuanshen-chen** [comment]
So that means when inference different samples, we just generate x_k as a noise randomly without x_0, unlike training process：generate x_k from x_0?

**Comment by jpthu17** [comment]
> So that means when inference different samples, we just generate x_k as a noise randomly without x_0, unlike training process：generate x_k from x_0?

Yes. In the training stage, diffusion models perform a forward process and require inputting x_0. While in the inference stage, diffusion models perform an inverse process and only need to sample a noise input.
