### ISSUE TITLE
Question about the two stage training

### ISSUE THREAD

**Issue by Code-kunkun** [jpthu17/DiffusionRet#7]
Thanks for your excellent work, but i have some questions about the two stage training
(1) In the generation training stage, the gradient exclude the diffusion model is set to False, so at the second stage, the discrimination loss has no impact to the training?
(2) Have you ever tried not using two-stage training approach? How is the effect?

**Comment by jpthu17** [comment]
> Thanks for your excellent work, but i have some questions about the two stage training (1) In the generation training stage, the gradient exclude the diffusion model is set to False, so at the second stage, the discrimination loss has no impact to the training? (2) Have you ever tried not using two-stage training approach? How is the effect?

(1) Yes, in the second stage we froze the feature encoder and only trained the diffusion model.
(2) We tried to fine-tune the full parameters in the second stage, but we got very poor results. According to our experience, the parameters of CLIP are very unstable in video-text training, and we guessed that if too many random parameters were introduced at once, the training would crash.

By the way, we do not try to fine-tune again after the second stage. We are not sure if this is going to be effective.

**Comment by Code-kunkun** [comment]
> (1) Yes, in the second stage we froze the feature encoder and only trained the diffusion model.
(2) We tried to fine-tune the full parameters in the second stage, but we got very poor results. According to our experience, the parameters of CLIP are very unstable in video-text training, and we guessed that if too many random parameters were introduced at once, the training would crash.
> 
> By the way, we do not try to fine-tune again after the second stage. We are not sure if this is going to be effective.

Thank you for your reply!!! So can I understand that the core of this paper is actually using the diffusion process for reranking?

**Comment by jpthu17** [comment]
> Thank you for your reply!!! So can I understand that the core of this paper is actually using the diffusion process for reranking?

Strictly speaking, it is not reranking the results; instead, we augment the cosine similarity with the similarity estimated by the diffusion model to get the final similarity. Reranking would involve computing the Top k candidate samples based on cosine similarity and subsequently reranking these Top k candidate samples using the diffusion model.

**Comment by Code-kunkun** [comment]
Thanks!!!
