### ISSUE TITLE
请问为什么用您这边的MSVD数据集，还没开始训练效果就这么差？

### ISSUE THREAD

**Issue by ghost** [jpthu17/DiffusionRet#8]
![image](https://github.com/jpthu17/DiffusionRet/assets/130990085/0d03de0c-a8ae-41f1-a5ad-46554399267d)

**Comment by jpthu17** [comment]
不应该出现这么差的结果，我这里会配置环境测试一下代码，可能会稍晚回复您

**Comment by ghost** [comment]
![image](https://github.com/jpthu17/DiffusionRet/assets/130990085/a8cbb10a-8ee1-4c2d-8e14-a7f61e0b77e8)
就是我测试了一下放到DiffusionRet里面MSVD里面是正常的，但是放到将MSVD放到HBI的Baseline里面就会出现，一开始就非常差劲，我不是很理解，上面的两张截图，都是将MSVD放到HBI里面的测试其实，因为HBI里面没有对于MSVD的dataloader，所以我把DiffusionRet的里面的关于MSVD的dataloader放到HBI里面，就会出现这种结果

**Comment by jpthu17** [comment]
HBI的代码并不支持在MSVD数据集上进行测试。因为MSVD数据集比较特殊，测试的时候一个文本对应多个视频，所以测试时需要对视频进行分组，你需要按照DiffusionRet的测试代码更改HBI的代码。

**Comment by ghost** [comment]
> HBI的代码并不支持在MSVD数据集上进行测试。因为MSVD数据集比较特殊，测试的时候一个文本对应多个视频，所以测试时需要对视频进行分组，你需要按照DiffusionRet的测试代码更改HBI的代码。

好的，非常感谢🙏🙏
